name: Build & Deploy Website to GitHub Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: ["main"]


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment.
# Skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      # - name: Install Swift
      #   uses: swift-actions/setup-swift@v2
      
      - name: Get swift version
        run: swift --version

      # - name: Generate Metadata
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: swift run generate-metadata

      - name: Generate Documentation
        run: ./deploy.sh generate Me

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
